dbgapi/msvc: __cplusplus
MSVC currently shows this build error:

 D:\therock\src\rocm-systems\projects\rocdbgapi\src\memory.h(146): error C2059: syntax error: '{'
 D:\therock\src\rocm-systems\projects\rocdbgapi\src\memory.h(146): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
 D:\therock\src\rocm-systems\projects\rocdbgapi\src\memory.h(146): error C2059: syntax error: '.'
 D:\therock\src\rocm-systems\projects\rocdbgapi\src\memory.h(149): error C2143: syntax error: missing ';' before '}'
 D:\therock\src\rocm-systems\projects\rocdbgapi\src\memory.h(149): error C2238: unexpected token(s) preceding ';'
 ...

The problem is MSVC and __cplusplus.  By default, MSVC has a bit of a
historical quirk: it reports 199711L (C++98) for the __cplusplus
macro, regardless of the actual language version you are using (like
C++17 or C++20).

As far I understood, Microsoft did this to avoid breaking legacy code
that relied on the old behavior, but it creates a headache for modern
cross-platform development.

To solve this, we have two options:

1) _MSVC_LANG

  This is a Microsoft-specific macro that correctly reports the C++
  standard version currently being targeted by the compiler.

2) /Zc:__cplusplus

  MSVC can be told to report the correct value for __cplusplus if you
  pass the compiler flag /Zc:__cplusplus.

Approach #2 does not work for us here, since we need this in
amd-dbgapi.h.in, and we can't always guarantee that every user of
dbgapi will have that flag enabled in their build system.

So this patch fixes it using approach #1.

Change-Id: Icb7ca9176fe8b4d8c6e19903c7c05ca724e26945
commit-id:22325de2